services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./src/main.py:/app/main.py
    networks:
      - hms
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      #- ./data:/var/lib/postgresql/data
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - hms
volumes:
  data:
networks:
  hms:
    driver: bridge